#!/bin/bash
while [[ $# > 1 ]]
do
	key="$1"

	case $key in
	    -u|--url)
	    URL="$2"
	    shift
	    ;;
	    -r|--report)
	    REPORT="$2"
	    shift
	    ;;
	    -l|--lang)
	    LANGUAGE="$2"
	    shift
	    ;;
	    *)
	    # unknown option
	    ;;
	esac
	shift
done

export BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"'$URL'"}}}'
./vendor/bin/behat -f pretty -o "${REPORT}/report.out" --no-colors --lang="${LANGUAGE}"
